"""
src/report.py
Generates downloadable Markdown and CSV reports from review comments.
"""

import csv
import io
from datetime import datetime


SEVERITY_EMOJI = {
    "critical": "🔴",
    "high":     "🟠",
    "medium":   "🟡",
    "low":      "🟢",
    "info":     "🔵",
}

CATEGORY_EMOJI = {
    "bug":             "🐛",
    "security":        "🔒",
    "performance":     "⚡",
    "style":           "✨",
    "maintainability": "🔧",
    "documentation":   "📝",
}


def generate_markdown_report(
    repo_name: str,
    comments: list[dict],
    parsed_files: list[dict],
) -> str:
    """Generate a comprehensive Markdown report."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # ── Summary stats ─────────────────────────────────────────────────────
    counts = {s: sum(1 for c in comments if c.get("severity") == s)
              for s in ["critical", "high", "medium", "low", "info"]}
    avg_conf = (sum(c.get("confidence", 0) for c in comments) / len(comments)
                if comments else 0)
    cat_counts = {}
    for c in comments:
        cat = c.get("category", "unknown")
        cat_counts[cat] = cat_counts.get(cat, 0) + 1

    lines = [
        f"# 🔍 CodeSight AI Review — `{repo_name}`",
        f"\n> Generated: {now}  ",
        f"> Files analysed: **{len(parsed_files)}**  ",
        f"> Total issues found: **{len(comments)}**  ",
        f"> Average confidence: **{avg_conf:.1f}%**",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ["critical", "high", "medium", "low", "info"]:
        emoji = SEVERITY_EMOJI.get(sev, "")
        lines.append(f"| {emoji} {sev.capitalize()} | {counts[sev]} |")

    lines += [
        "",
        "### By Category",
        "",
        "| Category | Count |",
        "|----------|-------|",
    ]
    for cat, cnt in sorted(cat_counts.items(), key=lambda x: -x[1]):
        emoji = CATEGORY_EMOJI.get(cat, "")
        lines.append(f"| {emoji} {cat.capitalize()} | {cnt} |")

    lines += ["", "---", "", "## 📁 Reviewed Files", ""]
    for pf in parsed_files:
        lines.append(
            f"- `{pf['filename']}` — "
            f"{pf.get('lines', 0)} lines · "
            f"{pf.get('num_functions', 0)} functions · "
            f"{pf.get('num_classes', 0)} classes"
        )

    lines += ["", "---", "", "## 🔍 Review Comments", ""]

    # Group by file
    by_file: dict[str, list[dict]] = {}
    for c in comments:
        fn = c.get("filename", "unknown")
        by_file.setdefault(fn, []).append(c)

    for filename, file_comments in by_file.items():
        lines += [f"\n### 📄 `{filename}`", ""]
        # Sort by severity
        severity_order = ["critical", "high", "medium", "low", "info"]
        file_comments.sort(
            key=lambda c: severity_order.index(c.get("severity", "info"))
            if c.get("severity") in severity_order else 99
        )
        for c in file_comments:
            sev   = c.get("severity", "info")
            conf  = c.get("confidence", 50)
            cat   = c.get("category", "style")
            verify = " ⚠️ **[VERIFY THIS]**" if conf < 40 else ""

            lines += [
                f"#### {SEVERITY_EMOJI.get(sev, '')} {c.get('title', 'Issue')}{verify}",
                "",
                f"**Severity:** `{sev}` | **Category:** `{cat}` | "
                f"**Location:** `{c.get('location', 'N/A')}` | "
                f"**Confidence:** `{conf}%`",
                "",
                c.get("comment", ""),
                "",
            ]
            if c.get("suggestion"):
                lines += [
                    "> 💡 **Suggestion:**",
                    f"> {c['suggestion']}",
                    "",
                ]
            lines.append("---")

    lines += [
        "",
        "---",
        "",
        "*Report generated by [CodeSight](https://github.com) — "
        "AI Code Review Agent built for CipherSchools.*",
    ]

    return "\n".join(lines)


def generate_csv_report(comments: list[dict]) -> str:
    """Generate a CSV report of all review comments."""
    output  = io.StringIO()
    fieldnames = [
        "filename", "location", "severity", "category",
        "title", "comment", "suggestion", "confidence",
    ]
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore",
                            lineterminator="\n")
    writer.writeheader()
    for c in comments:
        writer.writerow(c)
    return output.getvalue()
